var pathIconsCar = '../assets/images/png-cars/';

/**
 * Icons of Makes
 */
export const ICONS_MAKES = {
  abarth: require(pathIconsCar + 'abarth.png'),
  'alfa-romeo': require(pathIconsCar + 'alfa-romeo.png'),
  'aston-martin': require(pathIconsCar + 'aston-martin.png'),
  audi: require(pathIconsCar + 'audi.png'),
  bentley: require(pathIconsCar + 'bentley.png'),
  bmw: require(pathIconsCar + 'bmw.png'),
  cadillac: require(pathIconsCar + 'cadillac.png'),
  chevrolet: require(pathIconsCar + 'chevrolet.png'),
  citroen: require(pathIconsCar + 'citroen.png'),
  dacia: require(pathIconsCar + 'dacia.png'),
  ferrari: require(pathIconsCar + 'ferrari.png'),
  fiat: require(pathIconsCar + 'fiat.png'),
  ford: require(pathIconsCar + 'ford.png'),
  honda: require(pathIconsCar + 'honda.png'),
  hyundai: require(pathIconsCar + 'hyundai.png'),
  infiniti: require(pathIconsCar + 'infiniti.png'),
  jaguar: require(pathIconsCar + 'jaguar.png'),
  jeep: require(pathIconsCar + 'jeep.png'),
  kia: require(pathIconsCar + 'kia.png'),
  lamborghini: require(pathIconsCar + 'lamborghini.png'),
  lancia: require(pathIconsCar + 'lancia.png'),
  'land-rover': require(pathIconsCar + 'land-rover.png'),
  lexus: require(pathIconsCar + 'lexus.png'),
  mahindra: require(pathIconsCar + 'mahindra.png'),
  maserati: require(pathIconsCar + 'maserati.png'),
  mazda: require(pathIconsCar + 'mazda.png'),
  'mercedes-benz': require(pathIconsCar + 'mercedes-benz.png'),
  mini: require(pathIconsCar + 'mini.png'),
  mitsubishi: require(pathIconsCar + 'mitsubishi.png'),
  nissan: require(pathIconsCar + 'nissan.png'),
  opel: require(pathIconsCar + 'opel.png'),
  peugeot: require(pathIconsCar + 'peugeot.png'),
  porsche: require(pathIconsCar + 'porsche.png'),
  renault: require(pathIconsCar + 'renault.png'),
  seat: require(pathIconsCar + 'seat.png'),
  skoda: require(pathIconsCar + 'skoda.png'),
  smart: require(pathIconsCar + 'smart.png'),
  ssangyong: require(pathIconsCar + 'ssangyong.png'),
  subaru: require(pathIconsCar + 'subaru.png'),
  suzuki: require(pathIconsCar + 'suzuki.png'),
  tata: require(pathIconsCar + 'tata.png'),
  tesla: require(pathIconsCar + 'tesla.png'),
  toyota: require(pathIconsCar + 'toyota.png'),
  volkswagen: require(pathIconsCar + 'volkswagen.png'),
  volvo: require(pathIconsCar + 'volvo.png'),
  //Make icon that we don't have the icon
  circle_grey: require(pathIconsCar + 'circle_grey.png'),
};
